
GET http://localhost:3000/api-docs

### GET user
GET http://localhost:3000/user/

### create user
POST http://localhost:3000/user/
Content-Type: application/json

{
  "name": "Aora Doe",
  "email": "Aore@example.com",
  "password": "password1121"
}

### 
GET http://localhost:3000/user/6495c3b4ad694f7660acd417
Content-Type: application/json

### 
DELETE http://localhost:3000/user/6495c3b4ad694f7660acd417

### 
GET http://localhost:3000/task/

### 
POST http://localhost:3000/task/
Content-Type: application/json

{
  "title": "Visit sister Ann",
  "description": "ministering sister ann",
  "complete": false,
  "owner": "649bfccc940630cb66a478ba"
}

### 
GET http://localhost:3000/task/{id}

### 
POST http://localhost:3000/task/{id}

### 
DELETE http://localhost:3000/task/{id}

