
GET http://localhost:3000/api-docs

### GET user
GET http://localhost:3000/user/

### create user
POST http://localhost:3000/user/
Content-Type: application/json

{
  "name": "Amy Hunt",
  "email": "hunt@example.com",
  "password": "password1010"
}

### 
GET http://localhost:3000/user/649c18ec66c2f0114def0dbb
Content-Type: application/json

### 
DELETE http://localhost:3000/user/6495c5e4ad694f7660acd41b

### Get all tasks
GET http://localhost:3000/task/

### 
POST http://localhost:3000/task/
Content-Type: application/json

{
  "title": "Visiting",
  "description": "ministering sister May",
  "complete": false,
  "owner": "649bfccc940630cb66a478ba"
}

### 
GET http://localhost:3000/task/6495c619ad694f7660acd41f

### 
POST http://localhost:3000/task/{id}

### 
DELETE http://localhost:3000/task/{id}

